#!/bin/bash
# the number of remove AWS servers
N=8

# the number of nodes on each server
node=16

# public IPs --- This is the public IPs of AWS servers
pubIPsVar=([0]='18.135.17.154'
  [1]='18.133.238.135'
  [2]='18.171.177.78'
  [3]='18.171.177.233'
  [4]='18.170.224.66'
  [5]='3.10.198.201'
  [6]='3.8.48.231'
  [7]='18.133.244.123')

# Generate hosts.config
 rm hosts.config
 i=0
 while [ $i -le $(( N-1 )) ]; do
   j=0
   while [ $j -lt $(( node )) ]; do
      num=$(( i * node + j ))
      echo "$num 0.0.0.0 ${pubIPsVar[$i]} $(( $((2500 * $j)) + 10000 ))" >> hosts.config
      j=$(( j+1 ))
   done
   i=$(( i+1 ))
 done

# Clone config and keys to all remote AWS servers from github
 i=0; while [ $i -le $(( N-1 )) ]; do
 scp -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" /home/ubuntu/hosts.config ubuntu@${pubIPsVar[i]}:/home/ubuntu/kronos
 scp -o "StrictHostKeyChecking no" -r -i "/home/ubuntu/test_large.pem" /home/ubuntu/keys ubuntu@${pubIPsVar[i]}:/home/ubuntu/kronos & 
 i=$(( i+1 ))
 done

 
# Start Protocols at all remote AWS servers
 i=0
 while [ $i -le $(( N-1 )) ]; do   
    ssh -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]} "export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib; export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib; cd kronos; nohup ./start.sh 32 4 1 2000 5 $(( i * node )) $node 15000 > server-$i.out" &   
 i=$(( i+1 ))
 done

