#!/bin/bash

# the number of AWS servers to remove
N=

# the number of nodes on each server
node=

# public IPs --- This is the public IPs of AWS servers
pubIPsVar=(
[0]=''
)

 # Generate hosts.config
 rm hosts.config
 i=0
 while [ $i -le $(( N-1 )) ]; do
   j=0
   while [ $j -lt $(( node )) ]; do
      num=$(( i * node + j ))
      echo "$num 0.0.0.0 ${pubIPsVar[$i]} $(( $((2500 * $j)) + 10000 ))" >> hosts.config
      j=$(( j+1 ))
   done
   i=$(( i+1 ))
 done

# Clone config and keys to all remote AWS servers from github
 i=0; while [ $i -le $(( N-1 )) ]; do
 ssh -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]} "sudo rm -r /home/ubuntu/kronos/keys"
 scp -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" /home/ubuntu/hosts.config ubuntu@${pubIPsVar[i]}:/home/ubuntu/kronos
 scp -o "StrictHostKeyChecking no" -r -i "/home/ubuntu/test_large.pem" /home/ubuntu/keys ubuntu@${pubIPsVar[i]}:/home/ubuntu/kronos &
 i=$(( i+1 ))
 done
