#!/bin/bash
# the number of remove AWS servers
N=8

# the number of nodes on each server
node=16

# public IPs --- This is the public IPs of AWS servers
pubIPsVar=([0]='18.135.17.154'
  [1]='18.133.238.135'
  [2]='18.171.177.78'
  [3]='18.171.177.233'
  [4]='18.170.224.66'
  [5]='3.10.198.201'
  [6]='3.8.48.231'
  [7]='18.133.244.123')
 
# Download logs from all remote AWS servers to your local PC
i=0
while [ $i -le $(( N-1 )) ]
do
  scp -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]}:/home/ubuntu/env-log.txt /home/ubuntu/ver/env-log-$i.txt &
  i=$(( i+1 ))
done
 