#!/bin/bash
# the number of remove AWS servers
N=2

# the number of nodes on each server
node=16

# public IPs --- This is the public IPs of AWS servers
pubIPsVar=([0]='18.167.99.158'
  [1]='43.198.227.65')
 
 
# Download logs from all remote AWS servers to your local PC
i=0
while [ $i -le $(( N-1 )) ]
do
  scp -r -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]}:/home/ubuntu/kronos/log /home/ubuntu/total-log/log-$i&
  scp -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]}:/home/ubuntu/kronos/server-$i.out /home/ubuntu/total-log&
  i=$(( i+1 ))
done
 
