#!/bin/bash

# the number of AWS servers to remove
N=

# the number of nodes on each server
node=

# public IPs --- This is the public IPs of AWS servers
pubIPsVar=(
[0]=''
)
 
# Download logs from all remote AWS servers to your local PC
i=0
while [ $i -le $(( N-1 )) ]
do
  scp -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]}:/home/ubuntu/env-log.txt /home/ubuntu/ver/env-log-$i.txt &
  i=$(( i+1 ))
done
 