#!/bin/bash
# the number of remove AWS servers
N=4

# the number of nodes on each server
node=16

# public IPs --- This is the public IPs of AWS servers
pubIPsVar=([0]='54.198.78.194'
  [1]='54.162.246.216'
  [2]='16.162.161.200'
  [3]='18.167.51.240')

# Init all servers
 i=0; while [ $i -le $(( N-1 )) ]; do
 scp -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" /home/ubuntu/env-batch.sh ubuntu@${pubIPsVar[i]}:/home/ubuntu/  
 ssh -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]} "chmod 777 /home/ubuntu/env-batch.sh && sudo nohup ./env-batch.sh > env-log.txt" &
 i=$(( i+1 ))
 done
 
# Clone code,config and keys to all remote AWS servers from github
 i=0; while [ $i -le $(( N-1 )) ]; do
 ssh -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]} "git clone --branch speeddumbo-kronos-sqlite3 https://github.com/hidden-er/kronos.git"
 ssh -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]} "chmod -R 777 /home/ubuntu/kronos"  &
 i=$(( i+1 ))
 done
