#!/bin/bash
# the number of remove AWS servers
N=2

# the number of nodes on each server
node=16

# public IPs --- This is the public IPs of AWS servers
pubIPsVar=([0]='18.167.99.158'
  [1]='43.198.227.65')

 
# Start Protocols at all remote AWS servers
 i=0
 while [ $i -le $(( N-1 )) ]; do   
    ssh -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]} "export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib; export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib; cd kronos; nohup ./start.sh 8 4 1 1000 1 $(( i * node )) $node 20000 > server-$i.out" &   
 i=$(( i+1 )); 
 done

